src/Entity/Destinations.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DestinationsRepository")
 */
class Destinations
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TypeDestinations", inversedBy="destinations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name_sales;

    /**
     * @ORM\Column(type="json_array", nullable=true)
     */
    private $return_destinations;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cnrt_name;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $cnrt_code;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $cnrt_hour_start;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $cnrt_duration;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Stops", mappedBy="destination")
     */
    private $stops;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Services", mappedBy="destination")
     */
    private $destinations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Services", mappedBy="origin")
     */
    private $origin;

    public function __construct()
    {
        $this->stops = new ArrayCollection();
        $this->origin = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?TypeDestinations
    {
        return $this->type;
    }

    public function setType(?TypeDestinations $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getNameSales(): ?string
    {
        return $this->name_sales;
    }

    public function setNameSales(?string $name_sales): self
    {
        $this->name_sales = $name_sales;

        return $this;
    }

    public function getReturnDestinations()
    {
        return $this->return_destinations;
    }

    public function setReturnDestinations($return_destinations): self
    {
        $this->return_destinations = $return_destinations;

        return $this;
    }

    public function getCnrtName(): ?string
    {
        return $this->cnrt_name;
    }

    public function setCnrtName(?string $cnrt_name): self
    {
        $this->cnrt_name = $cnrt_name;

        return $this;
    }

    public function getCnrtCode(): ?string
    {
        return $this->cnrt_code;
    }

    public function setCnrtCode(?string $cnrt_code): self
    {
        $this->cnrt_code = $cnrt_code;

        return $this;
    }

    public function getCnrtHourStart(): ?string
    {
        return $this->cnrt_hour_start;
    }

    public function setCnrtHourStart(?string $cnrt_hour_start): self
    {
        $this->cnrt_hour_start = $cnrt_hour_start;

        return $this;
    }

    public function getCnrtDuration(): ?string
    {
        return $this->cnrt_duration;
    }

    public function setCnrtDuration(?string $cnrt_duration): self
    {
        $this->cnrt_duration = $cnrt_duration;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    /**
     * @return Collection|Stops[]
     */
    public function getStops(): Collection
    {
        return $this->stops;
    }

    public function addStop(Stops $stop): self
    {
        if (!$this->stops->contains($stop)) {
            $this->stops[] = $stop;
            $stop->setDestination($this);
        }

        return $this;
    }

    public function removeStop(Stops $stop): self
    {
        if ($this->stops->contains($stop)) {
            $this->stops->removeElement($stop);
            // set the owning side to null (unless already changed)
            if ($stop->getDestination() === $this) {
                $stop->setDestination(null);
            }
        }

        return $this;
    }
}

src/Form/DestinationsType.php
<?php

namespace App\Form;

use App\Entity\Destinations;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DestinationsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('name_sales')
            ->add('cnrt_name')
            ->add('cnrt_code')
            ->add('cnrt_hour_start')
            ->add('cnrt_duration')
            ->add('type')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Destinations::class,
        ]);
    }
}

src/Controller/DestinationsController.php
<?php

namespace App\Controller;

use App\Entity\Destinations;
use App\Form\DestinationsType;
use App\Repository\DestinationsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/backend/destinations")
 */
class DestinationsController extends AbstractController
{
    /**
     * @Route("/", name="destinations_list", methods={"GET"})
     */
    public function index(DestinationsRepository $destinationsRepository): Response
    {
        $page_info = array(
            'title' => 'Destinos',
            'breadcrumb' => array(
                $this->generateUrl('dashboard') => 'Principal',
                'none' => 'Destinos'
            )
        );
        return $this->render('destinations/list-all.html.twig', [
            'destinations' => $destinationsRepository->findAll(),
            'page_info' => $page_info
        ]);
    }

    /**
     * @Route("/new", name="destinations_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $destination = new Destinations();
        $form = $this->createForm(DestinationsType::class, $destination);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($destination);
            $entityManager->flush();

            return $this->redirectToRoute('destinations_list');
        }

        $page_info = array(
            'title' => 'Destinos',
            'breadcrumb' => array(
                $this->generateUrl('dashboard') => 'Principal',
                $this->generateUrl('destinations_list') => 'Destinos',
                'none' => 'Crear'
            )
        );

        return $this->render('destinations/new.html.twig', [
            'destination' => $destination,
            'form' => $form->createView(),
            'page_info' => $page_info
        ]);
    }

    /**
     * @Route("/{id}/edit", name="destinations_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Destinations $destination): Response
    {
        $form = $this->createForm(DestinationsType::class, $destination);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('destinations_list', [
                'id' => $destination->getId(),
            ]);
        }

        $page_info = array(
            'title' => 'Destinos',
            'breadcrumb' => array(
                $this->generateUrl('dashboard') => 'Principal',
                $this->generateUrl('destinations_list') => 'Destinos',
                'none' => 'Editar'
            )
        );

        return $this->render('destinations/edit.html.twig', [
            'destination' => $destination,
            'form' => $form->createView(),
            'page_info' => $page_info
        ]);
    }

    /**
     * @Route("/{id}", name="destinations_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Destinations $destination): Response
    {
        if ($this->isCsrfTokenValid('delete'.$destination->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($destination);
            $entityManager->flush();

            $data = [
                'status' => TRUE,
                'title' => 'Listo',
                'message' => 'Registro eliminado satisfactoriamente.',
                'redirUrl' => $this->generateUrl('destinations_list')
            ];

        } else {
            $data = [
                'status' => FALSE,
                'title' => 'Error',
                'message' => 'Error al eliminar el registro',
                'redirUrl' => NULL
            ];
        }

        return $this->json($data);
    }
}

templates/destinations/_form.html.twig
{{ form_start(form) }}
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Tipo de Destino</label>
        <div class="col-sm-3">
            {{ form_widget(form.type, { 'attr': {'class': 'form-control'} }) }}
        </div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Nombre</label>
        <div class="col-sm-4">{{ form_widget(form.name, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Nombre de Venta</label>
        <div class="col-sm-4">{{ form_widget(form.name_sales, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">CNRT Nombre</label>
        <div class="col-sm-4">{{ form_widget(form.cnrt_name, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">CNRT Código</label>
        <div class="col-sm-4">{{ form_widget(form.cnrt_code, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Hora de Salida</label>
        <div class="col-sm-4">{{ form_widget(form.cnrt_hour_start, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Duración</label>
        <div class="col-sm-4">{{ form_widget(form.cnrt_duration, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group row">
        <div class="col-sm-4 col-sm-offset-2">
            <a href="{{ path('destinations_list') }}" class="btn btn-white btn-sm" role="button">Cancelar</a>
            <button class="btn btn-primary btn-sm">Guardar</button>
        </div>
    </div>
{{ form_end(form) }}

templates/destinations/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {{page_title_base}}{{page_info.title}}
{% endblock %}
{% block breadcrumb %}
    {% embed 'layouts/breadcrumb.html.twig' %}{% endembed %}
{% endblock %}

{% block body %}
    <div class="wrapper wrapper-content animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Editar destino</h5>
                        <div class="ibox-tools">
                            <button class="btn btn-danger btn-xs float-right deleteItem" data-method="DELETE" data-token="{{ csrf_token('delete' ~ destination.id) }}" data-action="{{ path('destinations_delete', {'id': destination.id}) }}">{{ button_label|default('Borrar') }}</button>
                        </div>
                    </div>
                    <div class="ibox-content">
                    {% embed 'destinations/_form.html.twig' %}{% endembed %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/destinations/list-all.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {{page_title_base}}{{page_info.title}}
{% endblock %}
{% block breadcrumb %}
    {% embed 'layouts/breadcrumb.html.twig' %}
        {% block btnBreadcrumb %}
            <a href="{{path('destinations_new')}}" class="btn btn-primary" data-toggle="tooltip" title="Agregar Destino"><i class="fa fa-user-plus fa-fw"></i> Destino</a>
        {% endblock %}
    {% endembed %}
{% endblock %}

{% block body %}
    <div class="wrapper wrapper-content animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Listado de Destinos</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables" data-filename="destinos-listados">
                                <thead>
                                    <tr>
                                        <th>Tipo</th>
                                        <th>Nombre</th>
                                        <th>Nombre de Venta</th>
                                        <th>Destinos de Regreso</th>
                                        <th>CNRT Nombre</th>
                                        <th>CNRT Código</th>
                                        <th>Hora de Salida</th>
                                        <th>Duración</th>
                                        <th>Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for destination in destinations %}
                                        <tr>
                                            <td>{{ destination.type.name }}</td>
                                            <td>{{ destination.name }}</td>
                                            <td>{{ destination.nameSales }}</td>
                                            <td>{{ destination.returnDestinations ? destination.returnDestinations|json_encode : '' }}</td>
                                            <td>{{ destination.cnrtName }}</td>
                                            <td>{{ destination.cnrtCode }}</td>
                                            <td>{{ destination.cnrtHourStart ? destination.cnrtHourStart|date('Y-m-d H:i:s') : '' }}</td>
                                            <td>{{ destination.cnrtDuration }}</td>
                                            <td>
                                                <a href="{{ path('destinations_edit', {'id': destination.id}) }}">
                                                    <button class="btn btn-info btn-xs" type="button"><i class="fa fa-edit fa-fw"></i></button>
                                                </a>
                                            </td>
                                        </tr>
                                    {%endfor%}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/destinations/new.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {{page_title_base}}{{page_info.title}}
{% endblock %}
{% block breadcrumb %}
    {% embed 'layouts/breadcrumb.html.twig' %}{% endembed %}
{% endblock %}

{% block body %}
    <div class="wrapper wrapper-content animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Crear Destino</h5>
                    </div>
                    <div class="ibox-content">
                        {% embed 'destinations/_form.html.twig' %}{% endembed %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}