src/Entity/Stops.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StopsRepository")
 */
class Stops
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Destinations", inversedBy="stops")
     * @ORM\JoinColumn(nullable=false)
     */
    private $destination;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $keyname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="smallint")
     */
    private $position;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $time_trip;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price_card;

    /**
     * @ORM\Column(type="smallint")
     */
    private $fixed_point;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lat;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lng;

    /**
     * @ORM\Column(type="smallint")
     */
    private $buy_online;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDestination(): ?Destinations
    {
        return $this->destination;
    }

    public function setDestination(?Destinations $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getKeyname(): ?string
    {
        return $this->keyname;
    }

    public function setKeyname(string $keyname): self
    {
        $this->keyname = $keyname;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(int $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getTimeTrip(): ?float
    {
        return $this->time_trip;
    }

    public function setTimeTrip(?float $time_trip): self
    {
        $this->time_trip = $time_trip;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPriceCard(): ?float
    {
        return $this->price_card;
    }

    public function setPriceCard(?float $price_card): self
    {
        $this->price_card = $price_card;

        return $this;
    }

    public function getFixedPoint(): ?int
    {
        return $this->fixed_point;
    }

    public function setFixedPoint(int $fixed_point): self
    {
        $this->fixed_point = $fixed_point;

        return $this;
    }

    public function getLat(): ?string
    {
        return $this->lat;
    }

    public function setLat(?string $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?string
    {
        return $this->lng;
    }

    public function setLng(?string $lng): self
    {
        $this->lng = $lng;

        return $this;
    }

    public function getBuyOnline(): ?int
    {
        return $this->buy_online;
    }

    public function setBuyOnline(int $buy_online): self
    {
        $this->buy_online = $buy_online;

        return $this;
    }
}

src/Form/StopsType.php
<?php

namespace App\Form;

use App\Entity\Stops;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class StopsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('keyname')
            ->add('address')
            ->add('position')
            ->add('time_trip')
            ->add('price')
            ->add('price_card')
            ->add('fixed_point', ChoiceType::class,
                array(
                    'choices'  => array(
                        'Si' => '1',
                        'No' => '0',

                    )
                )
            )
            ->add('buy_online', ChoiceType::class,
                array(
                    'choices'  => array(
                        'Si' => '1',
                        'No' => '0',

                    )
                )
            )
            ->add('destination')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Stops::class,
        ]);
    }
}

src/Controller/StopsController.php
<?php

namespace App\Controller;

use App\Entity\Stops;
use App\Form\StopsType;
use App\Repository\StopsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/backend/stops")
 */
class StopsController extends AbstractController
{
    /**
     * @Route("/", name="stops_list", methods={"GET"})
     */
    public function index(StopsRepository $stopsRepository): Response
    {
        $page_info = array(
            'title' => 'Paradas',
            'breadcrumb' => array(
                $this->generateUrl('dashboard') => 'Principal',
                'none' => 'Paradas'
            )
        );

        return $this->render('stops/list-all.html.twig', [
            'stops' => $stopsRepository->findAll(),
            'page_info' => $page_info
        ]);
    }

    /**
     * @Route("/new", name="stops_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $stop = new Stops();
        $form = $this->createForm(StopsType::class, $stop);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($stop);
            $entityManager->flush();

            return $this->redirectToRoute('stops_list');
        }

        $page_info = array(
            'title' => 'Paradas',
            'breadcrumb' => array(
                $this->generateUrl('dashboard') => 'Principal',
                $this->generateUrl('stops_list') => 'Paradas',
                'none' => 'Crear'
            )
        );

        return $this->render('stops/new.html.twig', [
            'stop' => $stop,
            'form' => $form->createView(),
            'page_info' => $page_info
        ]);
    }

    /**
     * @Route("/{id}/edit", name="stops_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Stops $stop): Response
    {
        $form = $this->createForm(StopsType::class, $stop);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('stops_list', [
                'id' => $stop->getId(),
            ]);
        }

        $page_info = array(
            'title' => 'Paradas',
            'breadcrumb' => array(
                $this->generateUrl('dashboard') => 'Principal',
                $this->generateUrl('stops_list') => 'Paradas',
                'none' => 'Editar'
            )
        );

        return $this->render('stops/edit.html.twig', [
            'stop' => $stop,
            'form' => $form->createView(),
            'page_info' => $page_info
        ]);
    }

    /**
     * @Route("/{id}", name="stops_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Stops $stop): Response
    {
        if ($this->isCsrfTokenValid('delete'.$stop->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($stop);
            $entityManager->flush();

            $data = [
                'status' => TRUE,
                'title' => 'Listo',
                'message' => 'Registro eliminado satisfactoriamente.',
                'redirUrl' => $this->generateUrl('destinations_list')
            ];

        } else {
            $data = [
                'status' => FALSE,
                'title' => 'Error',
                'message' => 'Error al eliminar el registro',
                'redirUrl' => NULL
            ];
        }

        return $this->json($data);
    }
}

templates/stops/_form.html.twig
{{ form_start(form) }}
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Destino</label>
        <div class="col-sm-3">
            {{ form_widget(form.destination, { 'attr': {'class': 'form-control'} }) }}
        </div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Nombre</label>
        <div class="col-sm-4">{{ form_widget(form.name, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Clave</label>
        <div class="col-sm-4">{{ form_widget(form.keyname, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Direccion</label>
        <div class="col-sm-4">{{ form_widget(form.address, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Orden</label>
        <div class="col-sm-4">{{ form_widget(form.position, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Tiempo</label>
        <div class="col-sm-4">{{ form_widget(form.time_trip, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Tarifa</label>
        <div class="col-sm-4">{{ form_widget(form.price, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Tarifa Tarjeta</label>
        <div class="col-sm-4">{{ form_widget(form.price_card, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Compra Online</label>
        <div class="col-sm-4">{{ form_widget(form.buy_online, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="form-group  row">
        <label class="col-sm-2 col-form-label">Punto Fijo</label>
        <div class="col-sm-4">{{ form_widget(form.fixed_point, { 'attr': {'class': 'form-control'} }) }}</div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group row">
        <div class="col-sm-4 col-sm-offset-2">
            <a href="{{ path('stops_list') }}" class="btn btn-white btn-sm" role="button">Cancelar</a>
            <button class="btn btn-primary btn-sm">Guardar</button>
        </div>
    </div>
{{ form_end(form) }}

templates/stops/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {{page_title_base}}{{page_info.title}}
{% endblock %}
{% block breadcrumb %}
    {% embed 'layouts/breadcrumb.html.twig' %}
    {% endembed %}
{% endblock %}

{% block body %}
    <div class="wrapper wrapper-content animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Editar Parada</h5>
                        <div class="ibox-tools">
                            <button class="btn btn-danger btn-xs float-right deleteItem" data-method="DELETE" data-token="{{ csrf_token('delete' ~ stop.id) }}" data-action="{{ path('stops_delete', {'id': stop.id}) }}">{{ button_label|default('Borrar') }}</button>
                        </div>
                    </div>
                    <div class="ibox-content">
                       {% embed 'stops/_form.html.twig' %}{% endembed %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/stops/list-all.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {{page_title_base}}{{page_info.title}}
{% endblock %}
{% block breadcrumb %}
    {% embed 'layouts/breadcrumb.html.twig' %}
        {% block btnBreadcrumb %}
            <a href="{{path('stops_new')}}" class="btn btn-primary" data-toggle="tooltip" title="Agregar Parada"><i class="fa fa-user-plus fa-fw"></i> Parada</a>
        {% endblock %}
    {% endembed %}
{% endblock %}

{% block body %}
    <div class="wrapper wrapper-content animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Listado de Paradas</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover dataTables" data-filename="ciudades-listados">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Nombre</th>
                                        <th>Codigo</th>
                                        <th>Dirección</th>
                                        <th>Orden</th>
                                        <th>Tiempo</th>
                                        <th>Tarifa</th>
                                        <th>Tarjeta</th>
                                        <th>Punto Fijo</th>
                                        <th>Compra Online</th>
                                        <th>Opciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for stop in stops %}
                                    <tr>
                                        <td>{{ stop.id }}</td>
                                        <td>{{ stop.name }}</td>
                                        <td>{{ stop.keyname }}</td>
                                        <td>{{ stop.address }}</td>
                                        <td>{{ stop.position }}</td>
                                        <td>{{ stop.timeTrip }}</td>
                                        <td>{{ stop.price }}</td>
                                        <td>{{ stop.priceCard }}</td>
                                        <td>{{ stop.fixedPoint }}</td>
                                        <td>{%if stop.buyOnline == 1%}
                                                <i class="fa fa-check-circle text-success fa-fw"></i>
                                            {%else%}
                                                <i class="fa fa-times-circle text-danger fa-fw"></i>
                                            {%endif%}</td>
                                        <td>
                                            <a href="{{ path('stops_edit', {'id': stop.id}) }}">
                                                <button class="btn btn-info btn-xs" type="button"><i class="fa fa-edit fa-fw"></i></button>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/stops/new.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    {{page_title_base}}{{page_info.title}}
{% endblock %}
{% block breadcrumb %}
    {% embed 'layouts/breadcrumb.html.twig' %}
    {% endembed %}
{% endblock %}

{% block body %}
    <div class="wrapper wrapper-content animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Crear Parada</h5>
                    </div>
                    <div class="ibox-content">
                       {% embed 'stops/_form.html.twig' %}{% endembed %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}